# Generated by Django 2.2.5 on 2020-05-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.CharField(choices=[('Bench Press', 'Bench Press'), ('BB Curl', 'BB Curl'), ('DB Curl', 'DB Curl'), ('Dips', 'Dips'), ('Triceps Extention', 'Tricep Extention'), ('Back Squat', 'Back Squat'), ('Deadlift', 'Deadlift')], default='blank', max_length=30),
        ),
    ]
