# Generated by Django 2.2.5 on 2020-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitTrack', '0002_auto_20200524_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.CharField(choices=[('Bench Press', 'Bench Press'), ('Incline Bench Press', 'Incline Bench Press'), ('BB Bentover Row', ' BB Bentover Row'), ('Upright Row', 'Upright Row'), ('BB Curl', 'BB Curl'), ('DB Curl', 'DB Curl'), ('Dips', 'Dips'), ('Triceps Extention', 'Tricep Extention'), ('Back Squat', 'Back Squat'), ('Box Squat', 'Box Squat'), ('Romanian Deadlift', 'Romanian Deadlift'), ('Olympic Deadlift', 'Olympic Deadlift'), ('Military Press', 'Military Press'), ('Lateral Raise', 'Lateral Raise'), ('Sit-Ups', 'Sit-Ups'), ('Plank', 'Plank')], default='blank', max_length=30),
        ),
    ]
